# Generated by Django 2.2.17 on 2020-12-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_hjgfhj"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customtext",
            name="hjgfhj",
        ),
    ]
